[FileDialog]
history=file:///home/developer/data_annotated, file:///home/developer/data_annotated/active_vision, file:///home/developer/data_annotated/putkk, file:///home/developer/data_annotated/semantics3d_mod, file:///home/developer/data_annotated/semantics3d_raw
lastVisited=file:///home/developer/data_annotated/semantics3d_raw
qtVersion=5.5.1
shortcuts=file:, file:///home/developer
sidebarWidth=90
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xec\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xff\0\0\0\x1\0\0\0\0\0\0\0?\0\0\0\x1\0\0\0\0\0\0\0@\0\0\0\x1\0\0\0\0\0\0\0n\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0)
viewMode=Detail
